### ISSUE TITLE
java.lang.IncompatibleClassChangeError ApproximateHistogramAggregatorFactory

### ISSUE THREAD

**Issue by isublimity** [druid-io/tranquility#162]
I migrate from 1.1.1 to  Imply AP 1.2.0, try load Histogram Extension 

server.json
```
...
            {
              "fieldName": "in_price_per_click",
              "type": "approxHistogramFold",
              "name": "in_price_per_click",
              "resolution": 50,
              "numBuckets": 10,
              "lowerLimit": 0,
              "upperLimit": 200
            }
...
 
```
add : 
/home/igor/imply-1.2.0/dist/tranquility/conf/application.ini

```
-J-Ddruid.extensions.coordinates=["io.druid.extensions:druid-histogram:0.9.0"]
-J-Ddruid.extensions.localRepository=dist/druid/extensions_t
```

Try start - result 

```
Command[tranquility-server] failed, see logfile for more details: /home/igor/imply-1.2.0/var/sv/tranquility-server.log
```

in log : 

```
2016-04-26 22:35:19,505 [main] INFO  i.d.initialization.Initialization - Adding remote extension module[io.druid.query.aggregation.histogram.ApproximateHistogramDruidModule] for class[io.druid.initialization.DruidModule]
java.lang.IncompatibleClassChangeError: class io.druid.query.aggregation.histogram.ApproximateHistogramAggregatorFactory has interface io.druid.query.aggregation.AggregatorFactory as super class
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)

```

Where i wrong ? 
Thx)

**Comment by fjy** [comment]
@isublimity Please see the release notes for Druid 0.9.0: https://github.com/druid-io/druid/releases/tag/druid-0.9.0

Several of the configurations you are trying to use are deprecated. Please refer to http://imply.io/docs/latest/extensions about how to include extensions.

Additionally, in the future, please post these questions here: https://groups.google.com/forum/#!forum/imply-user-group

**Comment by isublimity** [comment]
I resolve my problem , if try load 0.9.0 extensions in tranquility => error 


```
/dist/tranquility/conf/application.ini
add 
-J-Ddruid.extensions.coordinates=["io.druid.extensions:druid-histogram:0.8.3"]
```
