### ISSUE TITLE
Scala Tranquility on for localhost druid

### ISSUE THREAD

**Issue by kucera-jan-cz** [druid-io/tranquility#186]
Hello everyone,

I am newbie in case of Druid and Tranquility and currently I am struggling with following use case:
- setup druid on external VM
- running Tranquility on localmachine

I have followed example at [ScalaExample.scala
](https://github.com/druid-io/tranquility/blob/master/core/src/test/scala/com/metamx/tranquility/example/ScalaExample.scala) 

Modified dimensions and changed `zookeeper.connect`, however when I am sending events I am receiving:

`[2016-07-08 14:15:57,615] WARN Emitting alert: [anomaly] Failed to create merged beam: druid:overlord/cb
{ } (com.metamx.tranquility.beam.ClusteredBeam)
java.lang.IllegalStateException: Failed to save new beam for identifier[druid:overlord/cb] timestamp[2016-07-08T00:00:00.000Z]
	at com.metamx.tranquility.beam.ClusteredBeam$$anonfun$2.applyOrElse(ClusteredBeam.scala:289)
	at com.metamx.tranquility.beam.ClusteredBeam$$anonfun$2.applyOrElse(ClusteredBeam.scala:286)
	at com.twitter.util.Future$$anonfun$rescue$1.apply(Future.scala:924)
	at com.twitter.util.Future$$anonfun$rescue$1.apply(Future.scala:922)
	at com.twitter.util.Promise$Transformer.liftedTree1$1(Promise.scala:112)
	at com.twitter.util.Promise$Transformer.k(Promise.scala:112)
	at com.twitter.util.Promise$Transformer.apply(Promise.scala:122)
	at com.twitter.util.Promise$Transformer.apply(Promise.scala:103)
	at com.twitter.util.Promise$$anon$1.run(Promise.scala:366)
	at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:178)
	at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:136)
	at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:207)
	at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:92)
	at com.twitter.util.Promise.runq(Promise.scala:350)
	at com.twitter.util.Promise.updateIfEmpty(Promise.scala:721)
	at com.twitter.util.ExecutorServiceFuturePool$$anon$2.run(FuturePool.scala:107)
....`

`Caused by: java.nio.channels.UnresolvedAddressException
	at sun.nio.ch.Net.checkAddress(Net.java:127)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:644)
	at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:108)
	at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779)
	at org.jboss.netty.channel.SimpleChannelHandler.connectRequested(SimpleChannelHandler.java:306)
	at org.jboss.netty.channel.SimpleChannelHandler.handleDownstream(SimpleChannelHandler.java:272)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
	at org.jboss.netty.channel.SimpleChannelHandler.connectRequested(SimpleChannelHandler.java:306)`

Is there possibility that Tranquility works only when Zookeper and Druid are on localhost? I am seeing f.e `IndexService.submit` method which creates `HttpPost `but does not set host..

**Comment by ncolomer** [comment]
I face the same issue... but in my case, tranquility (embedded in an external application) cannot reach my cluster's overlord:
```
2016-08-11T17:54:35.049+0200 [finagle/netty3-17] WARN  c.m.tranquility.finagle.FutureRetry$ - Transient error, will try again in 50 764 ms
com.twitter.finagle.ChannelWriteException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:8090 from service: disco!druid:overlord
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152)
	...
```

**Comment by ncolomer** [comment]
FYI, I solved the problem by setting the `druid.host` with the current host ip in the `_common/common.runtime.properties` configuration file (I use the [imply](https://imply.io/) druid distribution, but it should be something similar on the [standard](http://druid.io/) druid distribution).

**Comment by Igosuki** [comment]
FYI That's because the address is stored under druid/discovery/druid:overlord in zk which is druid.host whose default value is 'localhost'

**Comment by leixingzhi7** [comment]
I came across the same issue, have you solve it?

**Comment by Igosuki** [comment]
@leixingzhi7 You set druid.host in common.runtime.properties to be the machine's reachable IP address

**Comment by leixingzhi7** [comment]
Hello Igosuki, another question appear after setting the druid.host , the problem is =>
[ com.metamx.tranquility.druid.IndexServicePermanentException: Service[druid:overlord] call failed with status: 400 Bad Request] @Igosuki

**Comment by Igosuki** [comment]
That's something else entirely, a client is doing a malformed query (400)
and so says the logs... You'll have to do more debugging on your own

On Fri, Feb 24, 2017, 4:33 AM LEI CHEN <notifications@github.com> wrote:

Hello Igosuki, another question appear after setting the druid.host , the
problem is =>
[ com.metamx.tranquility.druid.IndexServicePermanentException:
Service[druid:overlord] call failed with status: 400 Bad Request] @Igosuki
<https://github.com/Igosuki>

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/druid-io/tranquility/issues/186#issuecomment-282194783>,
or mute the thread

**Comment by prathamesh13** [comment]
> FYI That's because the address is stored under druid/discovery/druid:overlord in zk which is druid.host whose default value is 'localhost'

@Igosuki I am facing some issue while using docker-druid image and tranquility. This could be helpful for debugging. How do i see what address is set under `druid/discovery/druid:overlord` . What is the command for checking that?
