### ISSUE TITLE
NoClassDefFoundError exception in tranquility 

### ISSUE THREAD

**Issue by antimion** [druid-io/tranquility#196]
Hi , i have some trouble with using tranquility kafka.
I have installed druid cluster on single machine, also installed tranquility.
Use default kafka,json with some modification from http://druid.io/docs/0.9.1.1/tutorials/tutorial-kafka.html. 

Tranquility starts fine, but when i try to put data like this ({"time": "2016-09-13T19:15:45Z", "url": "/foo/bar", "user": "alice", "latencyMs": 32}) into kafka , i receive this exception.

```
016-09-13 19:06:37,598 [KafkaConsumer-0] ERROR c.m.tranquility.kafka.KafkaConsumer - Exception: 
java.lang.NoClassDefFoundError: io/druid/indexing/common/task/AbstractTask
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_101]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[na:1.8.0_101]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_101]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[na:1.8.0_101]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_101]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[na:1.8.0_101]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[na:1.8.0_101]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_101]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[na:1.8.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_101]
	at io.druid.indexing.kafka.KafkaIndexTaskModule.getJacksonModules(KafkaIndexTaskModule.java:38) ~[na:na]
	at com.metamx.tranquility.druid.DruidGuicer.registerWithJackson$1(DruidGuicer.scala:80) ~[io.druid.tranquility-core-0.8.2.jar:0.8.2]
	at com.metamx.tranquility.druid.DruidGuicer.com$metamx$tranquility$druid$DruidGuicer$$toGuiceModule$1(DruidGuicer.scala:89) ~[io.druid.tranquility-core-0.8.2.jar:0.8.2]
	at com.metamx.tranquility.druid.DruidGuicer$$anonfun$3.apply(DruidGuicer.scala:127) ~[io.druid.tranquility-core-0.8.2.jar:0.8.2]
	at com.metamx.tranquility.druid.DruidGuicer$$anonfun$3.apply(DruidGuicer.scala:127) ~[io.druid.tranquility-core-0.8.2.jar:0.8.2]
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:418) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:418) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1233) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1223) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.collection.generic.Growable$class.loop$1(Growable.scala:54) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:57) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:183) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:45) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.collection.TraversableLike$class.$plus$plus(TraversableLike.scala:158) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.collection.immutable.List.$plus$plus(List.scala:196) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at com.metamx.tranquility.druid.DruidGuicer.<init>(DruidGuicer.scala:128) ~[io.druid.tranquility-core-0.8.2.jar:0.8.2]
	at com.metamx.tranquility.druid.DruidGuicer$.<init>(DruidGuicer.scala:138) ~[io.druid.tranquility-core-0.8.2.jar:0.8.2]
	at com.metamx.tranquility.druid.DruidGuicer$.<clinit>(DruidGuicer.scala) ~[io.druid.tranquility-core-0.8.2.jar:0.8.2]
	at com.metamx.tranquility.druid.DruidBeams$.makeFireDepartment(DruidBeams.scala:433) ~[io.druid.tranquility-core-0.8.2.jar:0.8.2]
	at com.metamx.tranquility.druid.DruidBeams$.fromConfigInternal(DruidBeams.scala:299) ~[io.druid.tranquility-core-0.8.2.jar:0.8.2]
	at com.metamx.tranquility.druid.DruidBeams$.fromConfig(DruidBeams.scala:204) ~[io.druid.tranquility-core-0.8.2.jar:0.8.2]
	at com.metamx.tranquility.kafka.KafkaBeamUtils$.createTranquilizer(KafkaBeamUtils.scala:40) ~[io.druid.tranquility-kafka-0.8.2.jar:0.8.2]
	at com.metamx.tranquility.kafka.KafkaBeamUtils.createTranquilizer(KafkaBeamUtils.scala) ~[io.druid.tranquility-kafka-0.8.2.jar:0.8.2]
	at com.metamx.tranquility.kafka.writer.TranquilityEventWriter.<init>(TranquilityEventWriter.java:64) ~[io.druid.tranquility-kafka-0.8.2.jar:0.8.2]
	at com.metamx.tranquility.kafka.writer.WriterController.createWriter(WriterController.java:171) ~[io.druid.tranquility-kafka-0.8.2.jar:0.8.2]
	at com.metamx.tranquility.kafka.writer.WriterController.getWriter(WriterController.java:98) ~[io.druid.tranquility-kafka-0.8.2.jar:0.8.2]
	at com.metamx.tranquility.kafka.KafkaConsumer$2.run(KafkaConsumer.java:231) ~[io.druid.tranquility-kafka-0.8.2.jar:0.8.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
Caused by: java.lang.ClassNotFoundException: io.druid.indexing.common.task.AbstractTask
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_101]
	... 43 common frames omitted
```

[common.runtime.properties.txt](https://github.com/druid-io/tranquility/files/470616/common.runtime.properties.txt)
[kafka.json.txt](https://github.com/druid-io/tranquility/files/470613/kafka.json.txt)
[runtime.properties.broker.txt](https://github.com/druid-io/tranquility/files/470614/runtime.properties.broker.txt)
[runtime.properties.coordinator.txt](https://github.com/druid-io/tranquility/files/470617/runtime.properties.coordinator.txt)
[runtime.properties.historical.txt](https://github.com/druid-io/tranquility/files/470615/runtime.properties.historical.txt)
[runtime.properties.middlemanager.txt](https://github.com/druid-io/tranquility/files/470618/runtime.properties.middlemanager.txt)
[runtime.properties.overlord.txt](https://github.com/druid-io/tranquility/files/470619/runtime.properties.overlord.txt)

**Comment by fangyeqing** [comment]
I have encountered the same problem with you, and find the answer in [google user group](https://groups.google.com/forum/#!topic/druid-user/y43-b1z3c3E)：

adding the "-Ddruid.extensions.loadList=[]" to the command
