### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class com.metamx.tranquility.druid.DruidBeams

### ISSUE THREAD

**Issue by Abhi11981198** [druid-io/tranquility#198]
Stack-trace : 
```
java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonInclude$Value  
at com.fasterxml.jackson.databind.cfg.MapperConfig.<clinit>(MapperConfig.java:45) ~[stormjar.jar:na]
    at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:535) ~[stormjar.jar:na]
    at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:461) ~[stormjar.jar:na]
    at com.metamx.common.scala.Jackson$class.newObjectMapper(Jackson.scala:67) ~[stormjar.jar:na]
    at com.metamx.common.scala.Jackson$.newObjectMapper(Jackson.scala:10) ~[stormjar.jar:na]
    at com.metamx.common.scala.Jackson$class.newObjectMapper(Jackson.scala:64) ~[stormjar.jar:na]
    at com.metamx.common.scala.Jackson$.newObjectMapper(Jackson.scala:10) ~[stormjar.jar:na]
    at com.metamx.common.scala.Jackson$class.$init$(Jackson.scala:14) ~[stormjar.jar:na]
    at com.metamx.common.scala.Jackson$.<init>(Jackson.scala:10) ~[stormjar.jar:na]
    at com.metamx.common.scala.Jackson$.<clinit>(Jackson.scala) ~[stormjar.jar:na]
    at com.metamx.tranquility.druid.DruidBeams$.<init>(DruidBeams.scala:107) ~[stormjar.jar:na] ](url)
```
Issue with jackson while initialization of object DruidBeams.

**Comment by zhouqianli** [comment]
I got same error on Flink cluster.  @Abhi11981198, did you resolve the issue?

**Comment by yuxiaojuan** [comment]
It is because the version of jackson is conflict. So DruidBeams can't init success.When you use DruidBeams,you will get java.lang.NoClassDefFoundError
I have changed the version of jackson to 2.4.4.It works.
