### ISSUE TITLE
tranquility core: Unrecognized field "name"

### ISSUE THREAD

**Issue by yorkart** [druid-io/tranquility#211]
use tranquility core api got error when  sink data to druid in flume
but ,  we run the demo in console is success.
can you give some advice

```
2017-03-21 20:02:56.391 WARN  [DruidTaskResolver[com.metamx.tranquility.druid.IndexService@539f7220]] (?.?:?)  - Poll failed, trying again at[2017-03-21T20:03:00.601+08:00].
org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "name" (Class org.apache.curator.x.discovery.ServiceInstance), not marked as ignorable
 at [Source: [B@4f533cf8; line: 1, column: 10] (through reference chain: org.apache.curator.x.discovery.ServiceInstance["name"])
	at org.codehaus.jackson.map.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:53)
	at org.codehaus.jackson.map.deser.StdDeserializationContext.unknownFieldException(StdDeserializationContext.java:246)
	at org.codehaus.jackson.map.deser.StdDeserializer.reportUnknownProperty(StdDeserializer.java:604)
	at org.codehaus.jackson.map.deser.StdDeserializer.handleUnknownProperty(StdDeserializer.java:590)
	at org.codehaus.jackson.map.deser.BeanDeserializer.handleUnknownProperty(BeanDeserializer.java:689)
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:514)
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:350)
	at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2402)
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1712)
	at org.apache.curator.x.discovery.details.JsonInstanceSerializer.deserialize(JsonInstanceSerializer.java:50)
	at org.apache.curator.x.discovery.details.ServiceCacheImpl.addInstance(ServiceCacheImpl.java:180)
	at org.apache.curator.x.discovery.details.ServiceCacheImpl.start(ServiceCacheImpl.java:83)
	at com.metamx.common.scala.net.curator.Disco$$anon$2.start(Disco.scala:63)
	at com.metamx.common.lifecycle.Lifecycle.start(Lifecycle.java:259)
	at com.metamx.common.scala.net.finagle.DiscoResolver$$anonfun$bind$1.apply(DiscoResolver.scala:46)
	at com.metamx.common.scala.net.finagle.DiscoResolver$$anonfun$bind$1.apply(DiscoResolver.scala:24)
	at com.twitter.util.Var$$anon$4.observe(Var.scala:330)
	at com.twitter.util.Var$class.observe(Var.scala:37)
	at com.twitter.util.Var$$anon$4.observe(Var.scala:302)
	at com.twitter.util.Var$$anon$3.register(Var.scala:100)
	at com.twitter.util.Event$class.respond(Event.scala:33)
	at com.twitter.util.Var$$anon$3.respond(Var.scala:98)
	at com.twitter.util.Event$$anon$2.register(Event.scala:42)
	at com.twitter.util.Event$class.toFuture(Event.scala:265)
	at com.twitter.util.Event$$anon$2.toFuture(Event.scala:40)
	at com.twitter.finagle.client.AddrMetadataExtraction$$anon$1.make(AddrMetadataExtraction.scala:53)
	at com.twitter.finagle.client.AddrMetadataExtraction$$anon$1.make(AddrMetadataExtraction.scala:29)
	at com.twitter.finagle.Stack$Module$$anonfun$toStack$1.apply(Stack.scala:440)
	at com.twitter.finagle.Stack$Module$$anonfun$toStack$1.apply(Stack.scala:440)
	at com.twitter.finagle.Stack$Node.make(Stack.scala:254)
	at com.twitter.finagle.factory.BindingFactory$Module$class.newStack$1(BindingFactory.scala:367)
	at com.twitter.finagle.factory.BindingFactory$Module$class.make(BindingFactory.scala:380)
	at com.twitter.finagle.factory.BindingFactory$$anon$4.make(BindingFactory.scala:398)
	at com.twitter.finagle.factory.BindingFactory$$anon$4.make(BindingFactory.scala:398)
	at com.twitter.finagle.Stack$Module$$anonfun$toStack$1.apply(Stack.scala:440)
	at com.twitter.finagle.Stack$Module$$anonfun$toStack$1.apply(Stack.scala:440)
	at com.twitter.finagle.Stack$Node.make(Stack.scala:254)
	at com.twitter.finagle.Stack$Module3$$anonfun$toStack$5.apply(Stack.scala:479)
	at com.twitter.finagle.Stack$Module3$$anonfun$toStack$5.apply(Stack.scala:478)
	at com.twitter.finagle.Stack$Node.make(Stack.scala:254)
	at com.twitter.finagle.Stack$Module1$$anonfun$toStack$3.apply(Stack.scala:457)
	at com.twitter.finagle.Stack$Module1$$anonfun$toStack$3.apply(Stack.scala:457)
	at com.twitter.finagle.Stack$Node.make(Stack.scala:254)
	at com.twitter.finagle.Stack$Module0$$anonfun$toStack$2.apply(Stack.scala:448)
	at com.twitter.finagle.Stack$Module0$$anonfun$toStack$2.apply(Stack.scala:448)
	at com.twitter.finagle.Stack$Node.make(Stack.scala:254)
	at com.twitter.finagle.Stack$Module0$$anonfun$toStack$2.apply(Stack.scala:448)
	at com.twitter.finagle.Stack$Module0$$anonfun$toStack$2.apply(Stack.scala:448)
	at com.twitter.finagle.Stack$Node.make(Stack.scala:254)
	at com.twitter.finagle.Stack$Module1$$anonfun$toStack$3.apply(Stack.scala:457)
	at com.twitter.finagle.Stack$Module1$$anonfun$toStack$3.apply(Stack.scala:457)
	at com.twitter.finagle.Stack$Node.make(Stack.scala:254)
	at com.twitter.finagle.Stack$Module0$$anonfun$toStack$2.apply(Stack.scala:448)
	at com.twitter.finagle.Stack$Module0$$anonfun$toStack$2.apply(Stack.scala:448)
	at com.twitter.finagle.Stack$Node.make(Stack.scala:254)
	at com.twitter.finagle.Stack$Module0$$anonfun$toStack$2.apply(Stack.scala:448)
	at com.twitter.finagle.Stack$Module0$$anonfun$toStack$2.apply(Stack.scala:448)
	at com.twitter.finagle.Stack$Node.make(Stack.scala:254)
	at com.twitter.finagle.Stack$Node.make(Stack.scala:254)
	at com.twitter.finagle.Stack$Module2$$anonfun$toStack$4.apply(Stack.scala:467)
	at com.twitter.finagle.Stack$Module2$$anonfun$toStack$4.apply(Stack.scala:466)
	at com.twitter.finagle.Stack$Node.make(Stack.scala:254)
	at com.twitter.finagle.Stack$Module1$$anonfun$toStack$3.apply(Stack.scala:457)
	at com.twitter.finagle.Stack$Module1$$anonfun$toStack$3.apply(Stack.scala:457)
	at com.twitter.finagle.Stack$Node.make(Stack.scala:254)
	at com.twitter.finagle.client.StdStackClient$class.newClient(StackClient.scala:400)
	at com.twitter.finagle.builder.CodecClient$Client$3.newClient(ClientBuilder.scala:1110)
	at com.twitter.finagle.builder.CodecClient.newClient(ClientBuilder.scala:1142)
	at com.twitter.finagle.builder.ClientBuilderClient$.newClient(ClientBuilder.scala:1008)
	at com.twitter.finagle.builder.ClientBuilderClient$.newService(ClientBuilder.scala:1044)
	at com.twitter.finagle.builder.ClientBuilder.build(ClientBuilder.scala:883)
	at com.metamx.tranquility.finagle.FinagleRegistry.mkclient(FinagleRegistry.scala:94)
	at com.metamx.tranquility.finagle.FinagleRegistry.connect(FinagleRegistry.scala:129)
	at com.metamx.tranquility.druid.CuratorOverlordLocator.connect(OverlordLocator.scala:50)
	at com.metamx.tranquility.druid.IndexService.com$metamx$tranquility$druid$IndexService$$client(IndexService.scala:61)
	at com.metamx.tranquility.druid.IndexService$$anonfun$call$1.apply(IndexService.scala:131)
	at com.metamx.tranquility.druid.IndexService$$anonfun$call$1.apply(IndexService.scala:131)
	at com.metamx.tranquility.finagle.FutureRetry$.onErrors(FutureRetry.scala:47)
	at com.metamx.tranquility.druid.IndexService.call(IndexService.scala:130)
	at com.metamx.tranquility.druid.IndexService.runningTasks(IndexService.scala:101)
	at com.metamx.tranquility.finagle.DruidTaskResolver$$anon$1.run(DruidTaskResolver.scala:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by yorkart** [comment]
update jar 
```
jackson-core-asl-1.8.8.jar 
jackson-mapper-asl-1.8.8.jar  
```
to 
```
 jackson-core-asl-1.9.13.jar
 jackson-mapper-asl-1.9.13.jar
```
is ok.

**Comment by ericssongator** [comment]
Hi yorkart, 
I did as you said, but still got the same error...here's my pom, is there anything wrong?
   <dependencies>
        <dependency>
            <groupId>org.codehaus.jackson</groupId>
            <artifactId>jackson-jaxrs</artifactId>
            <version>1.9.13</version>
        </dependency>
        <dependency>
            <groupId>org.codehaus.jackson</groupId>
            <artifactId>jackson-xc</artifactId>
            <version>1.9.13</version>
        </dependency>
        <dependency>
            <groupId>org.codehaus.jackson</groupId>
            <artifactId>jackson-core-asl</artifactId>
            <version>1.9.13</version>
        </dependency>
        <dependency>
            <groupId>org.codehaus.jackson</groupId>
            <artifactId>jackson-mapper-asl</artifactId>
            <version>1.9.13</version>
        </dependency>

        <dependency>
            <groupId>io.druid</groupId>
            <artifactId>tranquility-spark_2.10</artifactId>
            <version>0.8.2</version>
            
        </dependency>

        <dependency>
            <groupId>com.tencent.tdw</groupId>
            <artifactId>spark-toolkit_${scala.binary.version}</artifactId>
            <version>${tdw.toolkit.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.codehaus.jackson</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
            <scope>${compile.scope}</scope>
        </dependency>

 <dependency>
            <groupId>com.tencent.tdengine.api</groupId>
            <artifactId>tde-java</artifactId>
            <version>1.1.0</version>
            <scope>${compile.scope}</scope>
        </dependency>

        <dependency>
            <groupId>com.googlecode.xmemcached</groupId>
            <artifactId>xmemcached</artifactId>
            <version>2.0.0</version>
        </dependency>
    </dependencies>

**Comment by ericssongator** [comment]
I think I should ask another question, 'cause ur solution is correct. NOW my problem becomes it works in one spark environment, but not successful in another spark environment.....
