### ISSUE TITLE
DirectDruidTest intermittent failure

### ISSUE THREAD

**Issue by logarithm** [druid-io/tranquility#217]
`DirectDruidTest` sometimes fails with the next exception:

```
- Druid standalone - From config file - Smile mapper *** FAILED ***
[info]   com.metamx.common.ISE: Failed test
[info]   at com.metamx.tranquility.test.DirectDruidTest$$anonfun$3$$anonfun$apply$mcV$sp$3.apply(DirectDruidTest.scala:243)
[info]   at com.metamx.tranquility.test.DirectDruidTest$$anonfun$3$$anonfun$apply$mcV$sp$3.apply(DirectDruidTest.scala:216)
[info]   at com.metamx.tranquility.test.common.DruidIntegrationSuite$$anonfun$withDruidStack$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$3.apply(DruidIntegrationSuite.scala:203)
[info]   at com.metamx.tranquility.test.common.DruidIntegrationSuite$$anonfun$withDruidStack$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$3.apply(DruidIntegrationSuite.scala:202)
[info]   at com.metamx.tranquility.test.common.DruidIntegrationSuite$$anonfun$withOverlord$1.apply(DruidIntegrationSuite.scala:185)
[info]   at com.metamx.common.scala.control$$anonfun$retryOnErrors$1.apply(control.scala:47)
[info]   at com.metamx.common.scala.control$$anonfun$retryOnErrors$1.apply(control.scala:46)
[info]   at com.metamx.common.scala.control$$anonfun$withBackoff$1.apply(control.scala:58)
[info]   at com.metamx.common.scala.control$$anonfun$withBackoff$1.apply(control.scala:58)
[info]   at com.metamx.common.scala.control$.untilSome(control.scala:29)
[info]   ...
```

Any of tests under `DirectDruidTest` class might fail, and then the next build might be successful (or might not again). After debugging I found that it fails with assertion exception (`ArraySeq(false, false, false) did not equal List(true, false, true)`), and this assertion exception caused by 

```
com.twitter.finagle.NoBrokersAvailableException: No hosts are available for disco!druid:tranquility:firehose:xxx-018-0000-0000, Dtab.base=[], Dtab.local=[]
No hosts are available for disco!druid:tranquility:firehose:xxx-018-0000-0000, Dtab.base=[], Dtab.local=[]
```

But the root cause of this exception is still unclear to me.

**Comment by logarithm** [comment]
after PR #222 was applied we haven't faced with the same exception in tests. So we can consider this issue as fixed.
