### ISSUE TITLE
Tranquility should be able to push events to replicated beam if one of the partitioned replica is unreachable

### ISSUE THREAD

**Issue by nishantmonu51** [druid-io/tranquility#23]
We faced an issue in our metrics cluster, where one of the druid workers (1 partition out of 30) was unreachable via network but the task status was running, tranquility kept trying to send messages to the unreachable task and kept getting exceptions - 
```
2015-06-11 14:20:17,692 WARN  [finagle/netty3-3] com.metamx.tranquility.finagle.FutureRetry$ - Transient error, will try again in 29007 ms
java.io.IOException: Unable to push events to task: index_realtime_mmx_metrics_2015-06-11T14:00:00.000Z_10_0 (status = TaskRunning)
	at com.metamx.tranquility.druid.DruidBeam$$anonfun$4$$anonfun$apply$4$$anonfun$apply$6$$anonfun$apply$7$$anonfun$apply$3$$anonfun$applyOrElse$2.apply(DruidBeam.scala:160)
	at com.metamx.tranquility.druid.DruidBeam$$anonfun$4$$anonfun$apply$4$$anonfun$apply$6$$anonfun$apply$7$$anonfun$apply$3$$anonfun$applyOrElse$2.apply(DruidBeam.scala:146)
	at com.twitter.util.Future$$anonfun$map$1$$anonfun$apply$6.apply(Future.scala:863)
	at com.twitter.util.Try$.apply(Try.scala:13)
	at com.twitter.util.Future$.apply(Future.scala:90)
	at com.twitter.util.Future$$anonfun$map$1.apply(Future.scala:863)
	at com.twitter.util.Future$$anonfun$map$1.apply(Future.scala:863)
	at com.twitter.util.Future$$anonfun$flatMap$1.apply(Future.scala:824)
	
```

However, the replica task and other partitions were running fine, things were restored to normal on forcefully terminating the worker. 

Tranquility should be able to handle such a scenario and instead of getting stuck it can blacklist the unreachable partition and keep sending data to only the replica.

**Comment by gianm** [comment]
Did the task eventually fail? The idea is that tasks that are broken should fail, and then tranquility will see the failure and stop trying to send them data. So, IMO this should be addressed in the indexing service.

**Comment by gianm** [comment]
Tranquility can't safely ignore non-failed tasks, because otherwise the two replicas would get out of sync. It *will* stop pushing data when the task fails, though.

I think that if you want dead tasks to drop out of the cluster faster, you could reduce the RTR grace period from the 15 minute default.

**Comment by gianm** [comment]
Closing as I don't think there is much better tranquility can do here.
