### ISSUE TITLE
getting DefunctBeamException

### ISSUE THREAD

**Issue by dhuadaar** [druid-io/tranquility#230]
I have been ingesting messages at a very slow pace into  a Kafka topic but all my messages go into drop count with an `DefunctBeamException`. Earlier it seem to be some kind of network issue.

But all the network connectivity have been crossed check. As per mailing list suggestions, when I evaluated the capacity, I am comfortably having about 1.5 times the required capacity.

The logs doesn't seem to help much even in DEBUG Mode.

```2017-06-15 08:03:56,768 [finagle/netty3-33] WARN  c.m.tranquility.druid.TaskClient - Emitting alert: [anomaly] Loss of Druid redundancy: stag_betaout
{
  "dataSource" : "stag_betaout",
  "task" : "index_realtime_stag_betaout_2017-06-15T08:00:00.000Z_0_0",
  "status" : "TaskFailed"
}
2017-06-15 08:03:56,768 [finagle/netty3-33] INFO  c.metamx.emitter.core.LoggingEmitter - Event [{"feed":"alerts","timestamp":"2017-06-15T08:03:56.768Z","service":"tranquility","host":"localhost","severity":"anomaly","description":"Loss of Druid redundancy: stag_betaout","data":{"dataSource":"stag_betaout","task":"index_realtime_stag_betaout_2017-06-15T08:00:00.000Z_0_0","status":"TaskFailed"}}]
2017-06-15 08:03:56,769 [finagle/netty3-33] WARN  c.m.tranquility.beam.ClusteredBeam - Emitting alert: [anomaly] Beam defunct: druid:overlord/stag_betaout
{
  "eventCount" : 1,
  "timestamp" : "2017-06-15T08:00:00.000Z",
  "beam" : "MergingPartitioningBeam(DruidBeam(interval = 2017-06-15T08:00:00.000Z/2017-06-15T08:15:00.000Z, partition = 0, tasks = [index_realtime_stag_betaout_2017-06-15T08:00:00.000Z_0_0/stag_betaout-120-0000-0000]))"
}
com.metamx.tranquility.beam.DefunctBeamException: Tasks are all gone: index_realtime_stag_betaout_2017-06-15T08:00:00.000Z_0_0
    at com.metamx.tranquility.druid.DruidBeam$$anonfun$sendAll$2$$anonfun$6$$anonfun$apply$6.apply(DruidBeam.scala:115) ~[io.druid.tranquility-core-0.8.2.jar:0.8.2]
    at com.metamx.tranquility.druid.DruidBeam$$anonfun$sendAll$2$$anonfun$6$$anonfun$apply$6.apply(DruidBeam.scala:115) ~[io.druid.tranquility-core-0.8.2.jar:0.8.2]
    at scala.Option.getOrElse(Option.scala:121) ~[org.scala-lang.scala-library-2.11.7.jar:na]
    at com.metamx.tranquility.druid.DruidBeam$$anonfun$sendAll$2$$anonfun$6.apply(DruidBeam.scala:112) ~[io.druid.tranquility-core-0.8.2.jar:0.8.2]
    at com.metamx.tranquility.druid.DruidBeam$$anonfun$sendAll$2$$anonfun$6.apply(DruidBeam.scala:109) ~[io.druid.tranquility-core-0.8.2.jar:0.8.2]
    at com.twitter.util.Future$$anonfun$map$1$$anonfun$apply$6.apply(Future.scala:950) ~[com.twitter.util-core_2.11-6.30.0.jar:6.30.0]
    at com.twitter.util.Try$.apply(Try.scala:13) ~[com.twitter.util-core_2.11-6.30.0.jar:6.30.0]
    at com.twitter.util.Future$.apply(Future.scala:97) ~[com.twitter.util-core_2.11-6.30.0.jar:6.30.0]
    at com.twitter.util.Future$$anonfun$map$1.apply(Future.scala:950) ~[com.twitter.util-core_2.11-6.30.0.jar:6.30.0]
    at com.twitter.util.Future$$anonfun$map$1.apply(Future.scala:949) ~[com.twitter.util-core_2.11-6.30.0.jar:6.30.0]
    at com.twitter.util.Promise$Transformer.liftedTree1$1(Promise.scala:112) ~[com.twitter.util-core_2.11-6.30.0.jar:6.30.0]
    at com.twitter.util.Promise$Transformer.k(Promise.scala:112) ~[com.twitter.util-core_2.11-6.30.0.jar:6.30.0]
    at com.twitter.util.Promise$Transformer.apply(Promise.scala:122) ~[com.twitter.util-core_2.11-6.30.0.jar:6.30.0]
    at com.twitter.util.Promise$Transformer.apply(Promise.scala:103) ~[com.twitter.util-core_2.11-6.30.0.jar:6.30.0]
    at com.twitter.util.Promise$$anon$1.run(Promise.scala:366) ~[com.twitter.util-core_2.11-6.30.0.jar:6.30.0]
    at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:178) [com.twitter.util-core_2.11-6.30.0.jar:6.30.0]
    at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:136) [com.twitter.util-core_2.11-6.30.0.jar:6.30.0]
    at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:207) [com.twitter.util-core_2.11-6.30.0.jar:6.30.0]
    at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:92) [com.twitter.util-core_2.11-6.30.0.jar:6.30.0]
    at com.twitter.util.Promise.runq(Promise.scala:350) [com.twitter.util-core_2.11-6.30.0.jar:6.30.0]
    at com.twitter.util.Promise.updateIfEmpty(Promise.scala:721) [com.twitter.util-core_2.11-6.30.0.jar:6.30.0]
    at com.twitter.util.Promise.update(Promise.scala:694) [com.twitter.util-core_2.11-6.30.0.jar:6.30.0]
    at com.twitter.util.Promise.setException(Promise.scala:677) [com.twitter.util-core_2.11-6.30.0.jar:6.30.0]
    at com.twitter.finagle.netty3.ChannelConnector$$anon$2.operationComplete(Netty3Transporter.scala:69) [com.twitter.finagle-core_2.11-6.31.0.jar:6.31.0]
    at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409) [io.netty.netty-3.10.5.Final.jar:na]
    at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:400) [io.netty.netty-3.10.5.Final.jar:na]
    at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:362) [io.netty.netty-3.10.5.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:109) [io.netty.netty-3.10.5.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79) [io.netty.netty-3.10.5.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [io.netty.netty-3.10.5.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42) [io.netty.netty-3.10.5.Final.jar:na]
    at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [io.netty.netty-3.10.5.Final.jar:na]
    at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [io.netty.netty-3.10.5.Final.jar:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
    at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
```

Any suggestion on what it is ?

**Comment by hakangurel** [comment]
I had the same issue. In my case, it turns out that middle manager could not handle the amount of indexes that I was trying to create. 2 out of 6 were randomly failing with the exception you depicted.

I increased its memory and started working like a charm.
