### ISSUE TITLE
where can I  download tranquility-distribution-0.9.0

### ISSUE THREAD

**Issue by canghai118** [druid-io/tranquility#232]
the README.md says 

> The current distribution is: tranquility-distribution-0.9.0.

but I can get a 404 page.

I am using tranquility server for realtime ingestion, I use the data-sketch plugin.  and there is a error on startup
>java.lang.NoClassDefFoundError: io/druid/java/util/common/IAE
        at io.druid.query.aggregation.datasketches.theta.SketchMergeComplexMetricSerde.<init>(SketchMergeComplexMetricSerde.java:38)
        at io.druid.query.aggregation.datasketches.theta.SketchModule.configure(SketchModule.java:46)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
        at com.google.inject.spi.Elements.getElements(Elements.java:110)
        at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:198)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
        at com.google.inject.spi.Elements.getElements(Elements.java:110)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
        at com.google.inject.Guice.createInjector(Guice.java:96)
        at com.google.inject.Guice.createInjector(Guice.java:73)
        at com.google.inject.Guice.createInjector(Guice.java:62)

I think it's caused by mismatch druid version. So I am look for a tranquility release which against druid 0.10.x

**Comment by leventov** [comment]
There is no tranquility yet for Druid 0.10.x, this work is done here: https://github.com/druid-io/tranquility/tree/druid-0.10.1 but not finished yet

**Comment by canghai118** [comment]
OK. thank, I think I will solve my problem another way

**Comment by chenyongqing** [comment]
> OK. thank, I think I will solve my problem another way
Hi , I have the same problem， How do you deal with this problem ? I use the tranquility server veersion 0.8.2
