### ISSUE TITLE
java.lang.NoClassDefFoundError spark tranquility API

### ISSUE THREAD

**Issue by amoussoubaruch** [druid-io/tranquility#242]
hello,

I am trying to use tranquility with spark streaming. When i start jobs i got this error. I have not found class error 
Can 

`Caused by: java.lang.NoClassDefFoundError: io/druid/java/util/common/logger/Logger
	at io.druid.storage.hdfs.HdfsStorageDruidModule.<clinit>(HdfsStorageDruidModule.java:51)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 28 more
Caused by: java.lang.ClassNotFoundException: io.druid.java.util.common.logger.Logger
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 35 more

17/07/19 16:21:01 INFO scheduler.TaskSchedulerImpl: Removed TaskSet 1.0, whose tasks have all completed, from pool 
17/07/19 16:21:01 INFO scheduler.TaskSchedulerImpl: Cancelling stage 1
17/07/19 16:21:01 INFO scheduler.DAGScheduler: ResultStage 1 (foreachPartition at BeamRDD.scala:42) failed in 1.186 s due to Job aborted due to stage failure: Task 0 in stage 1.0 failed 1 times, most recent failure: Lost task 0.0 in stage 1.0 (TID 1, localhost, executor driver): java.lang.NoClassDefFoundError: Could not initialize class com.metamx.tranquility.druid.DruidGuicer$
	at com.metamx.tranquility.druid.DruidBeams$BuilderConfig$$anon$5.<init>(DruidBeams.scala:866)
	at com.metamx.tranquility.druid.DruidBeams$BuilderConfig.buildAll(DruidBeams.scala:861)
	at com.metamx.tranquility.druid.DruidBeams$Builder.buildBeam(DruidBeams.scala:739)
	at druidTest.SimpleEventBeamFactory$.instance(SimpleEvent.scala:108)
	at druidTest.SimpleEventBeamFactory$$anonfun$mkBeam$1.apply(SimpleEvent.scala:69)
	at druidTest.SimpleEventBeamFactory$$anonfun$mkBeam$1.apply(SimpleEvent.scala:69)
	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
	at druidTest.SimpleEventBeamFactory$.mkBeam(SimpleEvent.scala:69)
	at druidTest.SimpleEventBeamFactory.makeBeam(SimpleEvent.scala:60)
	at com.metamx.tranquility.spark.BeamRDD$$anonfun$propagate$1.apply(BeamRDD.scala:44)
	at com.metamx.tranquility.spark.BeamRDD$$anonfun$propagate$1.apply(BeamRDD.scala:43)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:925)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:925)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1944)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1944)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

Thanks in advance

**Comment by amoussoubaruch** [comment]
i thinks that this may be cause 

`17/07/19 16:21:01 WARN scheduler.TaskSetManager: Lost task 1.0 in stage 1.0 (TID 2, localhost, executor driver): java.util.ServiceConfigurationError: io.druid.initialization.DruidModule: Provider io.druid.storage.hdfs.HdfsStorageDruidModule could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at io.druid.initialization.Initialization.getFromExtensions(Initialization.java:157)
	at com.metamx.tranquility.druid.DruidGuicer.<init>(DruidGuicer.scala:124)
	at com.metamx.tranquility.druid.DruidGuicer$.<init>(DruidGuicer.scala:138)
	at com.metamx.tranquility.druid.DruidGuicer$.<clinit>(DruidGuicer.scala)
	at com.metamx.tranquility.druid.DruidBeams$BuilderConfig$$anon$5.<init>(DruidBeams.scala:866)
	at com.metamx.tranquility.druid.DruidBeams$BuilderConfig.buildAll(DruidBeams.scala:861)
	at com.metamx.tranquility.druid.DruidBeams$Builder.buildBeam(DruidBeams.scala:739)
	at druidTest.SimpleEventBeamFactory$.instance(SimpleEvent.scala:108)
	at druidTest.SimpleEventBeamFactory$$anonfun$mkBeam$1.apply(SimpleEvent.scala:69)
	at druidTest.SimpleEventBeamFactory$$anonfun$mkBeam$1.apply(SimpleEvent.scala:69)
	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
	at druidTest.SimpleEventBeamFactory$.mkBeam(SimpleEvent.scala:69)
	at druidTest.SimpleEventBeamFactory.makeBeam(SimpleEvent.scala:60)
	at com.metamx.tranquility.spark.BeamRDD$$anonfun$propagate$1.apply(BeamRDD.scala:44)
	at com.metamx.tranquility.spark.BeamRDD$$anonfun$propagate$1.apply(BeamRDD.scala:43)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:925)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:925)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1944)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1944)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: io/druid/java/util/common/logger/Logger
	at io.druid.storage.hdfs.HdfsStorageDruidModule.<clinit>(HdfsStorageDruidModule.java:51)
`

**Comment by ToonoW** [comment]
Do you resolve this problem?

**Comment by amoussoubaruch** [comment]
yes it's resolve!

**Comment by amoussoubaruch** [comment]
If you don't have lot of memory you can got this error
