### ISSUE TITLE
Kafka avro message parsing using tranquility

### ISSUE THREAD

**Issue by amoussoubaruch** [druid-io/tranquility#246]
Hi,
I'm using tranquility to ingest real time data from kafka to Druid. My data is store in kafka with avro format in kafka. 

I used this conf file for tranquility kafka. My kafka message is nested Json. So i try to use FlattenSpec to extract field in my schema.  I have a problem as you can see after config file i use. 

`{
  "dataSources": [
    {
      "spec": {
        "dataSchema": {
          "dataSource": "clients",
          "parser": {
            "type": "avro_stream",
            "avroBytesDecoder": {
              "type": "schema_repo",
              "subjectAndIdConverter": {
                "type": "avro_1124",
                "topic": "clients"
              }
            },
            "schemaRepository": {
              "type": "avro_1124_rest_client",
              "url": "http://registry.integration.com"
            },
            "parseSpec": {
				"format": "json",
				"flattenSpec": {
					"useFieldDiscovery": false,
					"fields": [
					  {
						"type": "path",
						"name": "hostname",
						"expr": "$.body.hostname"
					  },
					  {
						"type": "path",
						"name": "mac",
						"expr": "$.body.mac"
					  },
					  {
						"type": "path",
						"name": "ip",
						"expr": "$.body.ip"
					  },
					  {
						"type": "path",
						"name": "component",
						"expr": "$.body.component"
					  }
					]
				  },
              "timestampSpec": {
                "column": "timestamp",
                "format": "auto"
              },
              "dimensionsSpec" : {
			   "dimensions" : [],
			   "dimensionsExclusions": ["ignore_me"]
			  },
            }
          },
          "metricsSpec": [
            {
              "type": "count",
              "name": "body.version"
            }
          ],
          "granularitySpec": {
            "type": "uniform",
            "segmentGranularity": "hour",
            "queryGranularity": "none"
          }
        },
        "tuningConfig": {
          "type": "realtime",
          "maxRowsInMemory": 100000,
          "intermediatePersistPeriod": "PT200M",
          "windowPeriod": "PT200M"
        }
      },
      "properties": {
        "topicPattern": "clients",
        "topicPattern.priority": 1
      }
    }
  ],
  "properties": {
    "zookeeper.connect": "zookeeper.integration.com",
    "zookeeper.timeout": "PT20S",
    "druid.zk.paths.base": "/mnt/druid",
    "druid.discovery.curator.path": "druid/discovery",
    "druid.selectors.indexing.serviceName": "druid:overlord",
    "kafka.zookeeper.connect": "zookeeper.integration:2181",
    "kafka.group.id": "tranquility-kafka",
    "consumer.numThreads": 1,
    "commit.periodMillis": 15000,
    "reportDropsAsExceptions": false
  }
}`

My no parsing message 

`2017-07-24 10:10:50,694 [KafkaConsumer-CommitThread] INFO  c.m.tranquility.kafka.KafkaConsumer - Flushed {jcd_PlayerMetric={receivedCount=100, sentCount=0, droppedCount=0, unparseableCount=100}} pending messages in 1ms and committed offsets in 515ms. `

Can you help me please? 
Thanks in advance/

**Comment by ematos87** [comment]
Anyone know something about the problem above?

**Comment by skysaeed** [comment]
did you load Avro Plugin into Tranquility ? 
I tried to add the following lines into application.ini file in Tranquility/conf folder.
-Ddruid.extensions.directory=/Users/foo/bar/druid-0.12.0/extensions
-Ddruid.extensions.loadList=["druid-avro-extensions"]

now unparseable problem is solved but I get an error during parsing:

>ERROR c.m.tranquility.kafka.KafkaConsumer - Exception: 
java.lang.AbstractMethodError: io.druid.data.input.AvroStreamInputRowParser.parse(Ljava/lang/Object;)Lio/druid/data/input/InputRow;
	at com.metamx.tranquility.druid.DruidBeams$$anonfun$1$$anonfun$7.apply(DruidBeams.scala:182) ~[io.druid.tranquility-core-0.8.2.jar:0.8.2]
	at com.metamx.tranquility.druid.DruidBeams$$anonfun$1$$anonfun$7.apply(DruidBeams.scala:182) ~[io.druid.tranquility-core-0.8.2.jar:0.8.2]
