### ISSUE TITLE
io.druid.initialization.DruidModule: Provider io.druid.storage.hdfs.HdfsStorageDruidModule could not be instantiated

### ISSUE THREAD

**Issue by imewish** [druid-io/tranquility#253]
Hello, 

Im trying to start the Tranquility server process, with sample config provided in druid, using the following command ,

`bin/tranquility server -configFile <path_to_druid_distro>/conf-quickstart/tranquility/server.json`

When I run this, I'm getting an error as follows,

```
fs.HdfsStorageDruidModule could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at io.druid.initialization.Initialization.getFromExtensions(Initialization.java:152)
	at com.metamx.tranquility.druid.DruidGuicer.<init>(DruidGuicer.scala:124)
	at com.metamx.tranquility.druid.DruidGuicer$.<init>(DruidGuicer.scala:138)
	at com.metamx.tranquility.druid.DruidGuicer$.<clinit>(DruidGuicer.scala)
	at com.metamx.tranquility.druid.DruidBeams$.makeFireDepartment(DruidBeams.scala:406)
	at com.metamx.tranquility.druid.DruidBeams$.fromConfigInternal(DruidBeams.scala:291)
	at com.metamx.tranquility.druid.DruidBeams$.fromConfig(DruidBeams.scala:199)
	at com.metamx.tranquility.server.http.ServerMain$$anonfun$2.apply(ServerMain.scala:118)
	at com.metamx.tranquility.server.http.ServerMain$$anonfun$2.apply(ServerMain.scala:98)
	at com.metamx.common.scala.collection.package$MapLikeOps$$anonfun$strictMapValues$1.apply(package.scala:143)
	at com.metamx.common.scala.collection.package$MapLikeOps$$anonfun$strictMapValues$1.apply(package.scala:143)

 ```

How to resolve this? 

hepls would be appreciated

**Comment by Tanbouz** [comment]
Same here with Tranquility Kafka.

`[KafkaConsumer-0] ERROR c.m.tranquility.kafka.KafkaConsumer - Exception:`
`java.util.ServiceConfigurationError: io.druid.initialization.DruidModule: Provider io.druid.storage.hdfs.HdfsStorageDruidModule could not be instantiated`

I have no idea why tranquility depends on Hadoop/HDFS or how it internally works... I just want to use it to proxy a stream from Kafka to Druid.

**Possible workaround**
`tranquility kafka -configFile /path/to/tranquility/kafka.json -Ddruid.extensions.loadList='[]'`

It seems to bypass the issue by explicitly telling tranquility not to use that extension. I'm now getting other issues but don't think they are related. Still testing! ☀️
