### ISSUE TITLE
Problem in dimensionsSpec with "float" type

### ISSUE THREAD

**Issue by az3** [druid-io/tranquility#258]
Hello,

I used this guide to provide numeric dimensions: http://druid.io/docs/latest/ingestion/index.html#dimension-schema

But Tranquility kafka ingestion throws error. 

How can I define "float" and "time" dimensions in the tranquility ingestion config file.

Thanks.

- This is my Kafka record.
```
{
  "uuid": "36382327-b764-4982-8244-0430f099f255",
  "time": "2017-11-16T12:41:08Z",
  "topic": "openweather",
  "message": {
    "dt": "2017-11-16T11:50:00Z",
    "city": "İSTANBUL",
    "countryIso": "TR",
    "lat": 41.18,
    "lon": 29.61,
    "sunrise": "2017-11-16T04:51:13Z",
    "sunset": "2017-11-16T14:41:13Z",
    "temp": 13
  }
}
```

Float fields: "lat", "lon", "temp"
Time fields: "sunrise", "sunset"

- The below one includes "float" fields as dimensions.
```
{
  "dataSources": {
    "openweather-kafka3": {
      "spec": {
        "dataSchema": {
          "dataSource": "openweather-kafka3",
          "parser": {
            "type": "string",
            "parseSpec": {
              "format": "json",
              "flattenSpec": {
                "useFieldDiscovery": true,
                "fields": [
                  {
                    "type": "path",
                    "name": "timestamp",
                    "expr": "$.msg.dt"
                  },
                  {
                    "type": "path",
                    "name": "city",
                    "expr": "$.msg.city"
                  },
                  {
                    "type": "path",
                    "name": "countryIso",
                    "expr": "$.msg.countryIso"
                  },
                  {
                    "type": "path",
                    "name": "lat",
                    "expr": "$.msg.lat"
                  },
                  {
                    "type": "path",
                    "name": "lon",
                    "expr": "$.msg.lon"
                  },
                  {
                    "type": "path",
                    "name": "sunrise",
                    "expr": "$.msg.sunrise"
                  },
                  {
                    "type": "path",
                    "name": "sunset",
                    "expr": "$.msg.sunset"
                  },
                  {
                    "type": "path",
                    "name": "temp",
                    "expr": "$.msg.temp"
                  }
                ]
              },
              "timestampSpec": {
                "column": "timestamp",
                "format": "auto"
              },
              "dimensionsSpec": {
                "dimensions": [
                  "city",
                  "countryIso",
                  {
                    "type": "float",
                    "name": "lat"
                  },
                  {
                    "type": "float",
                    "name": "lon"
                  },
                  "sunrise",
                  "sunset",
                  {
                    "type": "float",
                    "name": "temp"
                  }
                ]
              }
            }
          },
          "granularitySpec": {
            "type": "uniform",
            "segmentGranularity": "hour",
            "queryGranularity": "none"
          },
          "metricsSpec": [
            
          ]
        },
        "ioConfig": {
          "type": "realtime"
        },
        "tuningConfig": {
          "type": "realtime",
          "maxRowsInMemory": "1000",
          "intermediatePersistPeriod": "PT10M",
          "windowPeriod": "PT10M"
        }
      },
      "properties": {
        "task.partitions": "1",
        "task.replicants": "1",
        "topicPattern": "openweather3"
      }
    }
  },
  "properties": {
    "zookeeper.connect": "localhost",
    "druid.discovery.curator.path": "/druid/discovery",
    "druid.selectors.indexing.serviceName": "druid/overlord",
    "commit.periodMillis": "15000",
    "consumer.numThreads": "2",
    "kafka.zookeeper.connect": "localhost",
    "kafka.group.id": "tq-openweather3-kafka3d"
  }
}
```

The error is below;
```
2017-11-16 12:50:33,428 [KafkaConsumer-0] INFO  c.m.t.kafka.writer.WriterController - Creating EventWriter for topic [openweather3] using dataSource [openweather-kafka3]
2017-11-16 12:50:33,469 [KafkaConsumer-0] INFO  o.a.c.f.imps.CuratorFrameworkImpl - Starting
2017-11-16 12:50:33,471 [KafkaConsumer-0] INFO  org.apache.zookeeper.ZooKeeper - Initiating client connection, connectString=localhost sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@1d62431e
2017-11-16 12:50:33,472 [KafkaConsumer-0-SendThread(localhost:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2017-11-16 12:50:33,473 [KafkaConsumer-0-SendThread(localhost:2181)] INFO  org.apache.zookeeper.ClientCnxn - Socket connection established to localhost/127.0.0.1:2181, initiating session
2017-11-16 12:50:33,475 [KafkaConsumer-0-SendThread(localhost:2181)] INFO  org.apache.zookeeper.ClientCnxn - Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x15fc4bdfd420016, negotiated timeout = 40000
2017-11-16 12:50:33,479 [KafkaConsumer-0-EventThread] INFO  o.a.c.f.state.ConnectionStateManager - State change: CONNECTED
2017-11-16 12:50:33,586 [KafkaConsumer-0] INFO  c.m.t.finagle.FinagleRegistry - Adding resolver for scheme[disco].
2017-11-16 12:50:34,690 [KafkaConsumer-0] INFO  o.h.validator.internal.util.Version - HV000001: Hibernate Validator 5.1.3.Final
2017-11-16 12:50:34,939 [KafkaConsumer-0] INFO  io.druid.guice.JsonConfigurator - Loaded class[class io.druid.guice.ExtensionsConfig] from props[druid.extensions.] as [ExtensionsConfig{searchCurrentClassloader=true, directory='extensions', hadoopDependenciesDir='hadoop-dependencies', loadList=null}]
2017-11-16 12:50:35,093 [KafkaConsumer-0] WARN  io.druid.segment.indexing.DataSchema - No metricsSpec has been specified. Are you sure this is what you want?
2017-11-16 12:50:35,134 [KafkaConsumer-CommitThread] INFO  c.m.tranquility.kafka.KafkaConsumer - Flushed 0 pending messages in 0ms and committed offsets in 2ms.
2017-11-16 12:50:35,136 [KafkaConsumer-0] ERROR c.m.tranquility.kafka.KafkaConsumer - Exception: 
java.lang.IllegalArgumentException: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: N/A; line: -1, column: -1] (through reference chain: java.util.ArrayList[2])
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:2774) ~[com.fasterxml.jackson.core.jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:2700) ~[com.fasterxml.jackson.core.jackson-databind-2.4.6.jar:2.4.6]
        at io.druid.segment.indexing.DataSchema.getParser(DataSchema.java:101) ~[io.druid.druid-server-0.9.0.jar:0.9.0]
        at com.metamx.tranquility.druid.DruidBeams$.fromConfigInternal(DruidBeams.scala:293) ~[io.druid.tranquility-core-0.8.0.jar:0.8.0]
        at com.metamx.tranquility.druid.DruidBeams$.fromConfig(DruidBeams.scala:199) ~[io.druid.tranquility-core-0.8.0.jar:0.8.0]
        at com.metamx.tranquility.kafka.KafkaBeamUtils$.createTranquilizer(KafkaBeamUtils.scala:40) ~[io.druid.tranquility-kafka-0.8.0.jar:0.8.0]
        at com.metamx.tranquility.kafka.KafkaBeamUtils.createTranquilizer(KafkaBeamUtils.scala) ~[io.druid.tranquility-kafka-0.8.0.jar:0.8.0]
        at com.metamx.tranquility.kafka.writer.TranquilityEventWriter.<init>(TranquilityEventWriter.java:64) ~[io.druid.tranquility-kafka-0.8.0.jar:0.8.0]
        at com.metamx.tranquility.kafka.writer.WriterController.createWriter(WriterController.java:171) ~[io.druid.tranquility-kafka-0.8.0.jar:0.8.0]
        at com.metamx.tranquility.kafka.writer.WriterController.getWriter(WriterController.java:98) ~[io.druid.tranquility-kafka-0.8.0.jar:0.8.0]
        at com.metamx.tranquility.kafka.KafkaConsumer$2.run(KafkaConsumer.java:231) ~[io.druid.tranquility-kafka-0.8.0.jar:0.8.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_152]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_152]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_152]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_152]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: N/A; line: -1, column: -1] (through reference chain: java.util.ArrayList[2])
        at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148) ~[com.fasterxml.jackson.core.jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:762) ~[com.fasterxml.jackson.core.jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseString(StdDeserializer.java:799) ~[com.fasterxml.jackson.core.jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:180) ~[com.fasterxml.jackson.core.jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:154) ~[com.fasterxml.jackson.core.jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:19) ~[com.fasterxml.jackson.core.jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:538) ~[com.fasterxml.jackson.core.jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:344) ~[com.fasterxml.jackson.core.jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1064) ~[com.fasterxml.jackson.core.jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:264) ~[com.fasterxml.jackson.core.jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:124) ~[com.fasterxml.jackson.core.jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:538) ~[com.fasterxml.jackson.core.jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:344) ~[com.fasterxml.jackson.core.jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1064) ~[com.fasterxml.jackson.core.jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:264) ~[com.fasterxml.jackson.core.jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:156) ~[com.fasterxml.jackson.core.jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:126) ~[com.fasterxml.jackson.core.jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:113) ~[com.fasterxml.jackson.core.jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:84) ~[com.fasterxml.jackson.core.jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:132) ~[com.fasterxml.jackson.core.jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:536) ~[com.fasterxml.jackson.core.jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:344) ~[com.fasterxml.jackson.core.jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1064) ~[com.fasterxml.jackson.core.jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:264) ~[com.fasterxml.jackson.core.jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:156) ~[com.fasterxml.jackson.core.jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:126) ~[com.fasterxml.jackson.core.jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:113) ~[com.fasterxml.jackson.core.jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:84) ~[com.fasterxml.jackson.core.jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:132) ~[com.fasterxml.jackson.core.jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:41) ~[com.fasterxml.jackson.core.jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:2769) ~[com.fasterxml.jackson.core.jackson-databind-2.4.6.jar:2.4.6]
        ... 15 common frames omitted
2017-11-16 12:50:35,137 [KafkaConsumer-0] INFO  c.m.tranquility.kafka.KafkaConsumer - Shutting down - attempting to flush buffers and commit final offsets
2017-11-16 12:50:35,141 [KafkaConsumer-0] INFO  org.apache.zookeeper.ZooKeeper - Session: 0x15fc4bdfd420016 closed
2017-11-16 12:50:35,141 [KafkaConsumer-0-EventThread] INFO  org.apache.zookeeper.ClientCnxn - EventThread shut down
2017-11-16 12:50:35,142 [KafkaConsumer-0] INFO  k.c.ZookeeperConsumerConnector - [tq-openweather3-kafka3d_ore-di-druid04-1510836604221-a5f43565], ZKConsumerConnector shutting down
2017-11-16 12:50:35,148 [KafkaConsumer-0] INFO  k.c.ZookeeperTopicEventWatcher - Shutting down topic event watcher.
2017-11-16 12:50:35,148 [KafkaConsumer-0] INFO  k.consumer.ConsumerFetcherManager - [ConsumerFetcherManager-1510836604308] Stopping leader finder thread
2017-11-16 12:50:35,148 [KafkaConsumer-0] INFO  k.c.ConsumerFetcherManager$LeaderFinderThread - [tq-openweather3-kafka3d_ore-di-druid04-1510836604221-a5f43565-leader-finder-thread], Shutting down
2017-11-16 12:50:35,149 [KafkaConsumer-0] INFO  k.c.ConsumerFetcherManager$LeaderFinderThread - [tq-openweather3-kafka3d_ore-di-druid04-1510836604221-a5f43565-leader-finder-thread], Shutdown completed
2017-11-16 12:50:35,149 [KafkaConsumer-0] INFO  k.consumer.ConsumerFetcherManager - [ConsumerFetcherManager-1510836604308] Stopping all fetchers
2017-11-16 12:50:35,149 [KafkaConsumer-0] INFO  kafka.consumer.ConsumerFetcherThread - [ConsumerFetcherThread-tq-openweather3-kafka3d_ore-di-druid04-1510836604221-a5f43565-0-0], Shutting down
2017-11-16 12:50:35,149 [tq-openweather3-kafka3d_ore-di-druid04-1510836604221-a5f43565-leader-finder-thread] INFO  k.c.ConsumerFetcherManager$LeaderFinderThread - [tq-openweather3-kafka3d_ore-di-druid04-1510836604221-a5f43565-leader-finder-thread], Stopped 
2017-11-16 12:50:35,150 [ConsumerFetcherThread-tq-openweather3-kafka3d_ore-di-druid04-1510836604221-a5f43565-0-0] INFO  kafka.consumer.SimpleConsumer - Reconnect due to socket error: java.nio.channels.ClosedByInterruptException
2017-11-16 12:50:35,150 [ConsumerFetcherThread-tq-openweather3-kafka3d_ore-di-druid04-1510836604221-a5f43565-0-0] INFO  kafka.consumer.ConsumerFetcherThread - [ConsumerFetcherThread-tq-openweather3-kafka3d_ore-di-druid04-1510836604221-a5f43565-0-0], Stopped 
2017-11-16 12:50:35,150 [KafkaConsumer-0] INFO  kafka.consumer.ConsumerFetcherThread - [ConsumerFetcherThread-tq-openweather3-kafka3d_ore-di-druid04-1510836604221-a5f43565-0-0], Shutdown completed
2017-11-16 12:50:35,151 [KafkaConsumer-0] INFO  k.consumer.ConsumerFetcherManager - [ConsumerFetcherManager-1510836604308] All connections stopped
2017-11-16 12:50:35,152 [ZkClient-EventThread-14-localhost] INFO  org.I0Itec.zkclient.ZkEventThread - Terminate ZkClient event thread.
2017-11-16 12:50:35,155 [KafkaConsumer-0] INFO  org.apache.zookeeper.ZooKeeper - Session: 0x15fc4bdfd420015 closed
2017-11-16 12:50:35,155 [main-EventThread] INFO  org.apache.zookeeper.ClientCnxn - EventThread shut down
2017-11-16 12:50:35,155 [KafkaConsumer-0] INFO  k.c.ZookeeperConsumerConnector - [tq-openweather3-kafka3d_ore-di-druid04-1510836604221-a5f43565], ZKConsumerConnector shutdown completed in 13 ms
2017-11-16 12:50:35,155 [KafkaConsumer-0] INFO  c.m.tranquility.kafka.KafkaConsumer - Finished clean shutdown.
2017-11-16 12:50:35,155 [KafkaConsumer-CommitThread] INFO  c.m.tranquility.kafka.KafkaConsumer - Commit thread interrupted.
2017-11-16 12:50:35,384 [tq-openweather3-kafka3d_ore-di-druid04-1510836604221-a5f43565_watcher_executor] INFO  k.c.ZookeeperConsumerConnector - [tq-openweather3-kafka3d_ore-di-druid04-1510836604221-a5f43565], stopping watcher executor thread for consumer tq-openweather3-kafka3d_ore-di-druid04-1510836604221-a5f43565
2017-11-16 12:50:35,385 [Thread-4] INFO  c.metamx.tranquility.kafka.KafkaMain - Initiating shutdown...
```

Note: This might be related to issue https://github.com/druid-io/tranquility/issues/247

**Comment by lvyahui8** [comment]
I also met this problem

**Comment by b-slim** [comment]
am not really expert on the `flatenSpec` but looking at the record is see the key is `message` while the Job sepc  has  `expr": "$.msg.sunset"` so am assuming you want to substitute `msg` with `message`
