### ISSUE TITLE
Tranquility with flink 1.3.2 and druid 0.11.0 fails

### ISSUE THREAD

**Issue by amalakar** [druid-io/tranquility#265]
I am seeing errors like the following, flink is unable to use the druid sink

```
2018-01-23 09:09:44,422 INFO  - 01/23/2018 09:09:44	Flat Map -> Filter -> Sink: Unnamed(3/4) switched to FAILED 
java.lang.NoSuchMethodError: com.google.common.net.HostAndPort.getHostText()Ljava/lang/String;
	at io.druid.server.DruidNode.init(DruidNode.java:101)
	at io.druid.server.DruidNode.<init>(DruidNode.java:77)
	at com.metamx.tranquility.druid.DruidGuicer$$anon$1.configure(DruidGuicer.scala:118)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:198)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at com.metamx.tranquility.druid.DruidGuicer.<init>(DruidGuicer.scala:128)
	at com.metamx.tranquility.druid.DruidGuicer$.<init>(DruidGuicer.scala:138)
	at com.metamx.tranquility.druid.DruidGuicer$.<clinit>(DruidGuicer.scala)
	at com.metamx.tranquility.druid.DruidBeams$.makeFireDepartment(DruidBeams.scala:433)
	at com.metamx.tranquility.druid.DruidBeams$.fromConfigInternal(DruidBeams.scala:299)
	at com.metamx.tranquility.druid.DruidBeams$.fromConfig(DruidBeams.scala:252)
	at com.lyft.druidstream.druid.DruidSinkFactory.makeBeam(DruidSinkFactory.scala:38)
	at com.metamx.tranquility.flink.BeamFactory$class.tranquilizer(BeamFactory.scala:38)
	at com.lyft.druidstream.druid.DruidSinkFactory.tranquilizer$lzycompute(DruidSinkFactory.scala:17)
	at com.lyft.druidstream.druid.DruidSinkFactory.tranquilizer(DruidSinkFactory.scala:17)
	at com.metamx.tranquility.flink.BeamSink.open(BeamSink.scala:48)
	at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:36)
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:111)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.openAllOperators(StreamTask.java:376)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:253)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:702)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by amalakar** [comment]
PR fixing this issue: https://github.com/druid-io/tranquility/pull/266
