### ISSUE TITLE
missing dependencies causing com.metamx.common.parsers.JSONPathParser class not found error

### ISSUE THREAD

**Issue by dyanarose** [druid-io/tranquility#268]
This has been reported in a few places, but I don't believe that a specific issue has been raised.
see this thread: https://groups.google.com/forum/#!topic/druid-user/5afMWd17sbU and the associated maven solution to add:
```
<!-- https://mvnrepository.com/artifact/com.metamx/java-util -->
<dependency>
    <groupId>com.metamx</groupId>
    <artifactId>java-util</artifactId>
    <version>0.27.9</version>
</dependency>
<!-- https://mvnrepository.com/artifact/joda-time/joda-time -->
<dependency>
    <groupId>joda-time</groupId>
    <artifactId>joda-time</artifactId>
    <version>2.9.4</version>
</dependency>
```

and https://github.com/druid-io/tranquility/issues/184#issuecomment-231273433 with the associated sbt solution to add:
``` "com.metamx" % "java-util" % "0.27.9",```

The calling application shouldn't have to add these dependencies directly. They should be included in the tranquility dependency

**Comment by qiaojialin** [comment]
Hi, after adding these dependencies, I got another error:

`Exception in thread "main" java.lang.NoSuchMethodError: com.fasterxml.jackson.module.scala.deser.BigDecimalDeserializer$.handledType()Ljava/lang/Class;
	at com.fasterxml.jackson.module.scala.deser.NumberDeserializers$.<init>(ScalaNumberDeserializersModule.scala:49)
	at com.fasterxml.jackson.module.scala.deser.NumberDeserializers$.<clinit>(ScalaNumberDeserializersModule.scala)
	at com.fasterxml.jackson.module.scala.deser.ScalaNumberDeserializersModule$class.$init$(ScalaNumberDeserializersModule.scala:61)
	at com.fasterxml.jackson.module.scala.DefaultScalaModule.<init>(DefaultScalaModule.scala:19)
	at com.fasterxml.jackson.module.scala.DefaultScalaModule$.<init>(DefaultScalaModule.scala:35)
	at com.fasterxml.jackson.module.scala.DefaultScalaModule$.<clinit>(DefaultScalaModule.scala)
	at com.metamx.common.scala.Jackson$$anonfun$newObjectMapper$1.apply(Jackson.scala:70)
	at com.metamx.common.scala.Jackson$$anonfun$newObjectMapper$1.apply(Jackson.scala:68)
	at com.metamx.common.scala.Predef$EffectOps.withEffect(Predef.scala:44)
	at com.metamx.common.scala.Jackson$class.newObjectMapper(Jackson.scala:67)
	at com.metamx.common.scala.Jackson$.newObjectMapper(Jackson.scala:10)
	at com.metamx.common.scala.Jackson$class.newObjectMapper(Jackson.scala:64)
	at com.metamx.common.scala.Jackson$.newObjectMapper(Jackson.scala:10)
	at com.metamx.common.scala.Jackson$class.$init$(Jackson.scala:14)
	at com.metamx.common.scala.Jackson$.<init>(Jackson.scala:10)
	at com.metamx.common.scala.Jackson$.<clinit>(Jackson.scala)
	at com.metamx.tranquility.druid.DruidBeams$.<init>(DruidBeams.scala:107)
	at com.metamx.tranquility.druid.DruidBeams$.<clinit>(DruidBeams.scala)
	at com.metamx.tranquility.druid.DruidBeams.fromConfig(DruidBeams.scala)`
