### ISSUE TITLE
Manually kill on the page, this time window re querying and inserting real-time data is wrong.

### ISSUE THREAD

**Issue by 845999248** [druid-io/tranquility#270]
2018-04-09 06:02:47,813 [finagle/netty3-4] INFO  c.m.tranquility.druid.TaskClient - Task index_realtime_redmos_compress_hour_2018-04-09T06:00:00.000Z_0_0 status changed from TaskRunning -> TaskFailed
2018-04-09 06:02:47,822 [finagle/netty3-4] WARN  c.m.tranquility.druid.TaskClient - Emitting alert: [anomaly] Loss of Druid redundancy: redmos_compress_hour
{
  "dataSource" : "redmos_compress_hour",
  "task" : "index_realtime_redmos_compress_hour_2018-04-09T06:00:00.000Z_0_0",
  "status" : "TaskFailed"
}
2018-04-09 06:02:47,822 [finagle/netty3-6] WARN  c.m.tranquility.druid.TaskClient - Emitting alert: [anomaly] Loss of Druid redundancy: redmos_compress_hour
{
  "dataSource" : "redmos_compress_hour",
  "task" : "index_realtime_redmos_compress_hour_2018-04-09T06:00:00.000Z_0_0",
  "status" : "TaskFailed"
}
2018-04-09 06:02:47,848 [finagle/netty3-4] INFO  c.metamx.emitter.core.LoggingEmitter - Event [{"feed":"alerts","timestamp":"2018-04-09T06:02:47.837Z","service":"tranquility","host":"localhost","severity":"anomaly","description":"Loss of Druid redundancy: redmos_compress_hour","data":{"dataSource":"redmos_compress_hour","task":"index_realtime_redmos_compress_hour_2018-04-09T06:00:00.000Z_0_0","status":"TaskFailed"}}]
2018-04-09 06:02:47,848 [finagle/netty3-6] INFO  c.metamx.emitter.core.LoggingEmitter - Event [{"feed":"alerts","timestamp":"2018-04-09T06:02:47.837Z","service":"tranquility","host":"localhost","severity":"anomaly","description":"Loss of Druid redundancy: redmos_compress_hour","data":{"dataSource":"redmos_compress_hour","task":"index_realtime_redmos_compress_hour_2018-04-09T06:00:00.000Z_0_0","status":"TaskFailed"}}]
2018-04-09 06:02:47,862 [finagle/netty3-6] WARN  c.m.tranquility.beam.ClusteredBeam - Emitting alert: [anomaly] Beam defunct: druid:overlord/redmos_compress_hour
{
  "eventCount" : 1,
  "timestamp" : "2018-04-09T06:00:00.000Z",
  "beam" : "MergingPartitioningBeam(DruidBeam(interval = 2018-04-09T06:00:00.000Z/2018-04-09T07:00:00.000Z, partition = 0, tasks = [index_realtime_redmos_compress_hour_2018-04-09T06:00:00.000Z_0_0/redmos_compress_hour-006-0000-0000]))"
}
com.metamx.tranquility.beam.DefunctBeamException: Tasks are all gone: index_realtime_redmos_compress_hour_2018-04-09T06:00:00.000Z_0_0
	at com.metamx.tranquility.druid.DruidBeam$$anonfun$sendAll$2$$anonfun$6$$anonfun$apply$6.apply(DruidBeam.scala:115) ~[io.druid.tranquility-core-0.8.2.jar:0.8.2]
	at com.metamx.tranquility.druid.DruidBeam$$anonfun$sendAll$2$$anonfun$6$$anonfun$apply$6.apply(DruidBeam.scala:115) ~[io.druid.tranquility-core-0.8.2.jar:0.8.2]
	at scala.Option.getOrElse(Option.scala:121) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at com.metamx.tranquility.druid.DruidBeam$$anonfun$sendAll$2$$anonfun$6.apply(DruidBeam.scala:112) ~[io.druid.tranquility-core-0.8.2.jar:0.8.2]
	at com.metamx.tranquility.druid.DruidBeam$$anonfun$sendAll$2$$anonfun$6.apply(DruidBeam.scala:109) ~[io.druid.tranquility-core-0.8.2.jar:0.8.2]
	at com.twitter.util.Future$$anonfun$map$1$$anonfun$apply$6.apply(Future.scala:950) ~[com.twitter.util-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.util.Try$.apply(Try.scala:13) ~[com.twitter.util-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.util.Future$.apply(Future.scala:97) ~[com.twitter.util-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.util.Future$$anonfun$map$1.apply(Future.scala:950) ~[com.twitter.util-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.util.Future$$anonfun$map$1.apply(Future.scala:949) ~[com.twitter.util-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.util.Promise$Transformer.liftedTree1$1(Promise.scala:112) ~[com.twitter.util-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.util.Promise$Transformer.k(Promise.scala:112) ~[com.twitter.util-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.util.Promise$Transformer.apply(Promise.scala:122) ~[com.twitter.util-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.util.Promise$Transformer.apply(Promise.scala:103) ~[com.twitter.util-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.util.Promise$$anon$1.run(Promise.scala:366) ~[com.twitter.util-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:178) [com.twitter.util-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:136) [com.twitter.util-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:207) [com.twitter.util-core_2.11-6.30.0.jar:6.30.0]

**Comment by py463360578** [comment]
Did you sovle it?
