### ISSUE TITLE
Can tranquility work with latest guava version

### ISSUE THREAD

**Issue by Venkipullela** [druid-io/tranquility#275]
java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.sameThreadExecutor()Lcom/google/common/util/concurrent/ListeningExecutorService;
	at org.apache.curator.framework.listen.ListenerContainer.addListener(ListenerContainer.java:40)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.start(CuratorFrameworkImpl.java:254)

This is the error which i got while running my project with tranquility. I'm using latest version of guava (23.0) in my project. I cannot downgrade that version. Is there any workaround for this?

**Comment by windbender** [comment]
Also:

Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.net.HostAndPort.getHostText()Ljava/lang/String;

In my case I'm trying to integrate with code which requires newer versions of Guava and the newer versions have dropped this method.
