### ISSUE TITLE
tranquility server ignoring basic authentication properties

### ISSUE THREAD

**Issue by prathamesh13** [druid-io/tranquility#286]
Tranquility server is unable to send data to druid even after the properties _druidBeam.basicAuthUser_ and _druidBeam.basicAuthPass_ are provided in the config file. It seems to be ignoring the authentication details supplies are returns a 401 unauthorized. 

Attached stacktrace below: 

`11-22T05:00:00.000Z_0_0/status] with content: {"error":"Unauthorized request.","errorMessage":null,"errorClass":null,"host":"******************"}
2018-11-22 05:53:53,257 [finagle/netty3-1] WARN  c.m.tranquility.beam.ClusteredBeam - Emitting alert: [anomaly] Failed to propagate events: druid:overlord/pageviews
{
  "eventCount" : 1,
  "timestamp" : "2018-11-22T05:00:00.000Z",
  "beams" : "MergingPartitioningBeam(DruidBeam(interval = 2018-11-22T05:00:00.000Z/2018-11-22T06:00:00.000Z, partition = 0, tasks = [index_realtime_pageviews_2018-11-22T05:00:00.000Z_0_0/pageviews-005-0000-0000]))"
}
com.metamx.tranquility.druid.IndexServicePermanentException: Service[druid:overlord] call failed with status: 401 Unauthorized
        at com.metamx.tranquility.druid.IndexService$$anonfun$call$1$$anonfun$apply$17.apply(IndexService.scala:158) ~[io.druid.tranquility-core-0.8.2.jar:0.8.2]
        at com.metamx.tranquility.druid.IndexService$$anonfun$call$1$$anonfun$apply$17.apply(IndexService.scala:132) ~[io.druid.tranquility-core-0.8.2.jar:0.8.2]
        at com.twitter.util.Future$$anonfun$map$1$$anonfun$apply$6.apply(Future.scala:950) ~[com.twitter.util-core_2.11-6.30.0.jar:6.30.0]
        at com.twitter.util.Try$.apply(Try.scala:13) ~[com.twitter.util-core_2.11-6.30.0.jar:6.30.0]
        at com.twitter.util.Future$.apply(Future.scala:97) ~[com.twitter.util-core_2.11-6.30.0.jar:6.30.0]
        at com.twitter.util.Future$$anonfun$map$1.apply(Future.scala:950) ~[com.twitter.util-core_2.11-6.30.0.jar:6.30.0]`

The credentials provided in the config file are valid and works fine when running queries against a given datasource.

**Comment by prathamesh13** [comment]
@jon-wei Does the tranquility server supports basic authentication? I could see #277 was for supporting authentication. Does this fix address authentication for `tranquility-core_2.11` ?

**Comment by prathamesh13** [comment]
@jon-wei Do you have the link for 0.8.3 release. I couldn't find it on the wiki.

**Comment by prathamesh13** [comment]
@jon-wei Is 0.8.3 released yet? I couldn't find the binary for this release, only the source packages are listed under [releases](https://github.com/druid-io/tranquility/releases)

**Comment by jon-wei** [comment]
@prathamesh13 The binary is here: http://static.druid.io/tranquility/releases/tranquility-distribution-0.8.3.tgz

**Comment by prathamesh13** [comment]
Thanks @jon-wei . Basic authentication is working fine with tranquility 0.8.3!
