### ISSUE TITLE
Unable to sync to druid, No hosts are available for disco!druid:overlord

### ISSUE THREAD

**Issue by bjtthao** [druid-io/tranquility#296]
Druid and tranquility are the latest versions
My configuration
   {
   "dataSources" : [
      {
         "spec" : {
            "dataSchema" : {
               "parser" : {
                  "type" : "string",
                  "parseSpec" : {
                     "timestampSpec" : {
                        "format" : "auto",
                        "column" : "@timestamp"
                     },
                     "dimensionsSpec" : {
                        "dimensions" : [
                          "host", 
                          "http_host",
                          "status",
                          "agent"
                        ]
                     },
                     "format" : "json"
                  }
               },
               "dataSource" : "tranquility-1",
               "granularitySpec" : {
                  "segmentGranularity" : "hour",
                  "type" : "uniform",
                  "queryGranularity" : "minute"
               },
               "metricsSpec" : [
                  {
                     "type" : "count",
                     "name" : "cnt"
                  } 
               ]
            },
            "tuningConfig" : {
               "maxRowsInMemory" : "4",
               "type" : "realtime",
               "windowPeriod" : "PT120M",
               "intermediatePersistPeriod" : "PT5S"
            }
         },
         "properties" : {
            "topicPattern.priority" : "1",
            "topicPattern" : "tranquility"
         }
      }
   ],
   "properties" : {
       "zookeeper.connect" : "localhost:2182",
       "zookeeper.timeout" : "PT20S",
       "druid.selectors.indexing.serviceName" : "druid/overlord",
       "druid.discovery.curator.path" : "/druid/discovery",
       "kafka.zookeeper.connect" : "localhost:2181",
       "kafka.group.id" : "tranquility",
       "consumer.numThreads" : "10",
       "commit.periodMillis" : "15000",
       "reportDropsAsExceptions" : "false",
       "druidBeam.randomizeTaskId" : "true"
    }
}
Exception information:
 c.metamx.emitter.core.LoggingEmitter - Event [{"feed":"alerts","timestamp":"2019-05-08T07:31:23.646Z","service":"tranquility","host":"localhost","severity":"anomaly","description":"Failed to create merged beam: druid:overlord/applog-dnu","data":{"exceptionType":"java.lang.IllegalStateException","exceptionMessage":"Failed to save new beam for identifier[druid:overlord/applog-dnu] timestamp[2019-05-08T06:00:00.000Z]","exceptionStackTrace":"java.lang.IllegalStateException: Failed to save new beam for identifier[druid:overlord/applog-dnu] timestamp[2019-05-08T06:00:00.000Z]\n\tat com.metamx.tranquility.beam.ClusteredBeam$$anonfun$2.applyOrElse(ClusteredBeam.scala:289)\n\tat com.metamx.tranquility.beam.ClusteredBeam$$anonfun$2.applyOrElse(ClusteredBeam.scala:286)\n\tat com.twitter.util.Future$$anonfun$rescue$1.apply(Future.scala:924)\n\tat com.twitter.util.Future$$anonfun$rescue$1.apply(Future.scala:922)\n\tat com.twitter.util.Promise$Transformer.liftedTree1$1(Promise.scala:112)\n\tat com.twitter.util.Promise$Transformer.k(Promise.scala:112)\n\tat com.twitter.util.Promise$Transformer.apply(Promise.scala:122)\n\tat com.twitter.util.Promise$Transformer.apply(Promise.scala:103)\n\tat com.twitter.util.Promise$$anon$1.run(Promise.scala:366)\n\tat com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:178)\n\tat com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:136)\n\tat com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:207)\n\tat com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:92)\n\tat com.twitter.util.Promise.runq(Promise.scala:350)\n\tat com.twitter.util.Promise.updateIfEmpty(Promise.scala:721)\n\tat com.twitter.util.ExecutorServiceFuturePool$$anon$2.run(FuturePool.scala:107)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: com.twitter.finagle.NoBrokersAvailableException: No hosts are available for disco!druid:overlord, Dtab.base=[], Dtab.local=[]\n\tat com.twitter.finagle.NoStacktrace(Unknown Source)\n"}}]

2019-05-08 07:27:35,078 [ClusteredBeam-ZkFuturePool-73aa95a6-864b-49bf-8f7a-1bd6e168c586] WARN  c.m.tranquility.finagle.FutureRetry$ - Transient error, will try again in 16,740 ms
com.twitter.finagle.NoBrokersAvailableException: No hosts are available for disco!druid:overlord, Dtab.base=[], Dtab.local=[]
	at com.twitter.finagle.NoStacktrace(Unknown Source) ~[na:na]
2019-05-08 07:27:51,829 [Hashed wheel timer #1] WARN  c.m.tranquility.finagle.FutureRetry$ - Transient error, will try again in 23,088 ms
com.twitter.finagle.NoBrokersAvailableException: No hosts are available for disco!druid:overlord, Dtab.base=[], Dtab.local=[]
	at com.twitter.finagle.NoStacktrace(Unknown Source) ~[na:na]

**Comment by MichelCarroll** [comment]
Does anybody have more information on this? I'm getting the same problem. Tried both v0.8.3 and v0.8.2. Here's mine:

```
{
              "dataSources" : {
                "rc_metrics" : {
                  "spec" : {
                    "dataSchema" : {
                      "dataSource" : "metrics",
                      "parser" : {
                        "type" : "string",
                        "parseSpec" : {
                          "timestampSpec" : {
                            "column" : "timestamp",
                            "format" : "auto"
                          },
                          "dimensionsSpec" : {
                            "dimensionExclusions" : [
                              "timestamp",
                              "value"
                            ]
                          },
                          "format" : "json"
                        }
                      },
                      "granularitySpec" : {
                        "type" : "uniform",
                        "segmentGranularity" : "hour",
                        "queryGranularity" : "none"
                      },
                      "metricsSpec" : [
                        {
                          "type" : "count",
                          "name" : "count"
                        },
                        {
                          "name" : "value_sum",
                          "type" : "doubleSum",
                          "fieldName" : "value"
                        },
                        {
                          "fieldName" : "value",
                          "name" : "value_min",
                          "type" : "doubleMin"
                        },
                        {
                          "type" : "doubleMax",
                          "name" : "value_max",
                          "fieldName" : "value"
                        }
                      ]
                    },
                    "ioConfig" : {
                      "type" : "realtime"
                    },
                    "tuningConfig" : {
                      "type" : "realtime",
                      "maxRowsInMemory" : "100000",
                      "intermediatePersistPeriod" : "PT10M",
                      "windowPeriod" : "PT10M"
                    }
                  },
                  "properties" : {
                    "task.partitions" : "1",
                    "task.replicants" : "1"
                  }
                }

              },
              "properties" : {
                "zookeeper.connect" : "druid-zookeeper.infra:2181",
                "druid.discovery.curator.path" : "/druid/discovery",
                "druid.selectors.indexing.serviceName" : "druid/overlord",
                "http.port" : "8200",
                "http.threads" : "8",
                "druidBeam.randomizeTaskId": "true"
              }
            }
```
